export const COMMON_HARDWOODS = [
	"Ash",
	"Black Limba",
	"Bloodwood",
	"Cherry",
	"Douglas Fir",
	"Hickory",
	"Maple",
	"Maple (Ambrosia)",
	"Maple (Birdseye)",
	"Maple (Curly)",
	"Oak (Red)",
	"Oak (White)",
	"Padauk",
	"Pine",
	"Poplar",
	"Purple Heart",
	"Tigerwood",
	"Walnut (Black)",
	"Walnut (Peruvian)",
	"Wenge",
	"Zebrawood",
]
